In [ ]:
import numpy as np
arry1 = np.array([1,2,3])

In [18]:
print(arry1)

[1 2 3]


In [19]:
print(type(arry1))

<class 'numpy.ndarray'>


In [20]:
print(arry1.shape)

(3,)


In [21]:
arry1[2]=5

In [22]:
print(arry1)

[1 2 5]


In [24]:
arry2 =np.array([[1,2,3],[3,4,5]])
print(arry2)

[[1 2 3]
 [3 4 5]]


In [25]:
arry2[1][1]

4

In [27]:
print(arry2.shape)

(2, 3)


In [28]:
arry2[1,-1]

5

In [33]:
arry3 = np.array(["Nigeria", "India", "China", "USA", "Mexico"])
arry3

array(['Nigeria', 'India', 'China', 'USA', 'Mexico'], dtype='<U7')

In [54]:
arrR =np.arange(0,20,2)
print(arrR)

[ 0  2  4  6  8 10 12 14 16 18]


In [36]:
arrL = np.linspace(0,10,20)
print(arrL)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [43]:
arr = np.random.rand(10)   #this random 10 number selected
print(arr)

[0.63275069 0.33943902 0.52534669 0.72770178 0.76587509 0.60699824
 0.33094973 0.53341592 0.66645682 0.30757288]


In [41]:
arrd = np.random.rand(3,4)
print(arrd)

[[0.84724766 0.32903184 0.093639   0.58855761]
 [0.75061478 0.99341474 0.92251192 0.54723318]
 [0.74654187 0.97663345 0.45060534 0.57003874]]


In [47]:
print(np.zeros(10))
print("/n")
print(np.zeros((2,3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0.]
 [0. 0. 0.]]


In [55]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
